### ISSUE TITLE
program crash while playing auto generated sound

### ISSUE THREAD

**Issue by Jb200126** [ZaneAhmed/Keytar#1]
When i play the auto generated sound i can not exit out of the program.
os: Linuxmx
 I was playing the auto generated sound on a acer travelmate b spin. Suddenly the program could not close anymore.

**Comment by Jb200126** [comment]
tone: 65.0
amplitude: 3.3

**Comment by ZaneAhmed** [comment]
Can't reproduce 😁😁

**Comment by Jb200126** [comment]
Talked with the developer about the problem and it is fixed now. I really need the program for my work. Thanks for help!
